# Generated by Django 3.2.5 on 2021-07-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('birth', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('movie_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='imdbratings.movies')),
                ('rating', models.FloatField()),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdbratings.movies')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdbratings.people')),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdbratings.movies')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdbratings.people')),
            ],
        ),
    ]
